#### [Source](https://medium.com/better-programming/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d#3338)


In [1]:
import numpy as np

# 1. Vectorized Operations vs list
- Numpy vs list
    + `[+]` more compact, especially when there’s more than one dimension
    + `[+]` faster than lists when the `operations` can be vectorized
    + `[-]` slower than lists when `append` elements to the end ( np.array O(N) vs list O(1) )
    + `[-]` usually homogeneous: can only work fast with elements of one type

In [2]:
# list
A = [1,2,3]
print([x*2 for x in A])

# np array
A = np.array([1,2,3])
print(A * 2)

[2, 4, 6]
[2 4 6]


In [3]:
# list
A = [1,2,3]
B = [4,5,6]
print([x+y for x,y in zip(A,B)])

# np array
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A + B)

[5, 7, 9]
[5 7 9]


# 2.  1D Arrays

## 2.1 Init

In [4]:
# From list
A = np.array([1., 2., 3.], dtype=np.float64)
A

array([1., 2., 3.])

In [5]:
# zeros
A = np.zeros(shape=(3,), dtype=np.int)
A

array([0, 0, 0])

In [6]:
# ones
A = np.ones(shape=3, dtype=np.float32)
A

array([1., 1., 1.], dtype=float32)

In [7]:
# empty
A = np.empty(shape=3, dtype=np.int)
A

array([4607182418800017408, 4611686018427387904, 4613937818241073152])

In [8]:
# full
A = np.full(shape=3, fill_value=2, dtype=np.int)
A

array([2, 2, 2])

## 2.2 Init range
#### arange(start,stop,step)

In [9]:
np.arange(1,6,2)

array([1, 3, 5])

#### linspace(start,stop,num)

In [10]:
np.linspace(0,0.5,6)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5])

## 2.3 Init Random
#### Int

In [11]:
# Int: [low,high)
np.random.randint(low=0, high=10, size=(3,))

array([8, 9, 0])

#### Uniform

In [12]:
# Uniform distribution: [0,1)
np.random.rand(3)

array([0.08515078, 0.23804527, 0.16423571])

In [13]:
# Uniform distribution: [low,high)
np.random.uniform(low=1, high=10, size=3)

array([7.87711892, 1.56013139, 8.5082266 ])

#### Normal

In [14]:
# Normal distribution: mean = 0, std = 1
np.random.randn(3)

array([ 0.65116668, -0.86049474, -0.97055788])

In [15]:
# Normal distribution: mean = loc, std = scale
np.random.normal(loc=5,scale=2,size=3)

array([5.24625201, 4.01017   , 4.7216163 ])

## 2.4 Copy
<img src="assets/7.png" width="750"/>


## 2.5 Indexing, slicing
<img src="assets/6.png" width="750"/>


## 2.6 Boolean Indexing

<img src="assets/8.png" width="750"/>
<img src="assets/9.png" width="750"/>


## 2.7 Vector operations
+ numpy do vector ops at C++ level

#### Vector vs vector
<img src="assets/10.png" width="750"/>

#### Vector vs scalar
<img src="assets/11.png" width="750"/>

#### Vector math ops

<img src="assets/12.png" width="750"/>

#### Vector dot and cross product

<img src="assets/13.png" width="750"/>

#### Vector Trigonometry math ops

<img src="assets/14.png" width="750"/>

#### Vector floor, ceil, round

<img src="assets/15.png" width="750"/>

## 2.8 Aggregate
#### max. min, mean, std
<img src="assets/16.png" width="750"/>

#### sort
- **Note**: np.array doesn't have descending sort. `reversed` the array after sorted
<img src="assets/17.png" width="750"/>

#### search


In [16]:
A = np.array([1,5,6,7,9,2,4,3,8,3])
elem = 3

# where: Find all occurrences (look through all elements of the array) O(N)
print(np.where(A==elem)[0])


# searchsorted: Need A to be sorted first. O(NlogN) then O(logN)
A.sort()
np.searchsorted(A, elem)

[7 9]


2

## 2.9 Comparing floats

In [17]:
print(np.allclose(a=(0.1+0.2), b=0.31, atol=1e-1))
print(np.allclose(a=(0.1+0.2), b=0.31, atol=1e-6))
print(np.allclose(a=(0.1+0.2), b=0.3000001, atol=1e-6))

True
False
True


## 2.10 Iterate through np.array

In [18]:
A = np.array([1,5,6,7,9,2,4,3,8,3])
for idx, val in np.ndenumerate(A):
    print(idx, val)

(0,) 1
(1,) 5
(2,) 6
(3,) 7
(4,) 9
(5,) 2
(6,) 4
(7,) 3
(8,) 8
(9,) 3


# 3. Matrices/vectors - 2D Arrays

## 3.1 Init
<img src="assets/18.png" width="750"/>


In [19]:
A = np.array(
    [[1., 2., 3.],
     [4., 5., 6.]], dtype=np.float64)

## 3.2 Init Random
<img src="assets/19.png" width="750"/>


## 3.3 Indexing, Slicing
<img src="assets/20.png" width="750"/>

## 3.4 Axis argument

<img src="assets/21.png" width="750"/>

## 3.5 Matrix ops

#### Matrix vs matrix
<img src="assets/22.png" width="750"/>

#### Matrix vs vector, scalar
<img src="assets/23.png" width="750"/>


## 3.6 Transpose and reshape, flatten
#### Transpose
<img src="assets/24.png" width="750"/>

#### reshape, flatten
- `-1`: calculate one of the dimension sizes automatically
+ `None`: A shortcut for np.newaxis

<img src="assets/25.png" width="750"/>

<img src="assets/26.png" width="750"/>


## 3.7 Matrix manipulations
#### Join matrix/vector - matrix/vector
- `vstack`, `hstack`

<img src="assets/27.png" width="750"/>

#### Join matrix/vector - array
- `vstack` works as expected
- use `column_stack` instead of `hstack`

<img src="assets/28.png" width="750"/>

#### split
- `vsplit`, `hsplit`

<img src="assets/29.png" width="750"/>


#### Repeating
- `tile`, `repeat`

<img src="assets/30.png" width="750"/>

#### Delete
- `delete`

<img src="assets/31.png" width="750"/>

#### Insert
- `insert`

<img src="assets/32.png" width="750"/>

#### Append
- `append`

<img src="assets/33.png" width="750"/>

#### Padding
- `pad`

<img src="assets/34.png" width="750"/>

#### Meshgrids
- Method 1: slowest

<img src="assets/37.png" width="750"/>

- Method 2

<img src="assets/35.png" width="750"/>

- Method 3: Most optimized

<img src="assets/35.png" width="750"/>


## 3.8 Aggregate
- sum, min, max, argmin, argmax, mean, std, var

<img src="assets/38.png" width="750"/>

<img src="assets/39.png" width="750"/>

- all, any

<img src="assets/40.png" width="750"/>



## 3.9 sort

<img src="assets/41.png" width="750"/>

####  sorts the array by the first column
- `a[a[:,0].argsort()]` 
- `argsort` returns an array of indices of the original array after sorting.


<img src="assets/42.png" width="750"/>

####  sorts the multiple columns

```python
a = a[a[:,2].argsort()]
a = a[a[:,1].argsort(kind='stable')]
a = a[a[:,0].argsort(kind='stable')]
```

<img src="assets/43.png" width="750"/>

#### lexsort
- `flipud`: flips the matrix in the up-down direction (axis=0), same as `a[::-1,...]`
- `a[np.lexsort(np.flipud(a[2,5].T))]`: sorts by column 2 first and then (where the values in column 2 are equal) by column 5.
- `a[np.lexsort(np.flipud(a.T))]`: sorts by all columns in left-to-right order

<img src="assets/44.png" width="750"/>



# 4. Tensors - 3D Array

## 4.1 Init

<img src="assets/45.png" width="750"/>

## 4.2 stacking
- `hstack`, `vstack`, `dstack`

<img src="assets/46.png" width="750"/>

## 4.3 concat
- `concatenate`

<img src="assets/47.png" width="750"/>

## 4.4 move, swap axis
- `moveaxis`

<img src="assets/48.png" width="750"/>

- `swapaxes`

<img src="assets/49.png" width="750"/>


## 4.5 Einstein summation

<img src="assets/50.png" width="750"/>
